"""v2.0 sanity check (PRD 0A.2 Calibration row, 0A.4 week of 2026-10-18): compare the uncalibrated baseline with
public points. This is not calibration: no fit uses these points, and every output keeps its badge.

Globe at Night: SQM readings are compared directly; naked-eye limiting magnitudes (LM 1-7, star-chart method)
are converted to zenith sky brightness by inverting NELM = 7.93 - 5 log10(10^(4.316 - SQM/5) + 1). Most GaN
entries are taken 20:00-22:00, before commercial lights go off, so they should read brighter than the model's
01:00-04:00 SQM window.
"""
from __future__ import annotations

import math

import numpy as np

from engine import bortle
from engine.grid import sample_bilinear


def sqm_from_nelm(nelm: float) -> float | None:
    x = 10 ** ((7.93 - nelm) / 5) - 1
    if x <= 0:
        return None
    return 5 * (4.316 - math.log10(x))


def globe_at_night(grid, L15, natural_mag, rows):
    out = []
    for r in rows:
        if r["cloud"] and r["cloud"].lower() not in ("clear", "0", ""):
            continue
        model = float(bortle.total_mag(sample_bilinear(grid, L15, r["lon"], r["lat"])[0], natural_mag))
        if r["sqm"]:
            obs, kind = r["sqm"], "sqm"
        elif r["limiting_mag"]:
            obs, kind = sqm_from_nelm(r["limiting_mag"]), "nelm"
            if obs is None:
                continue
        else:
            continue
        out.append({**r, "kind": kind, "obs_mag": round(obs, 2), "model_mag": round(model, 2), "residual": round(model - obs, 2)})
    def stats(rows):
        res = np.array([o["residual"] for o in rows])
        if not len(res):
            return None, None
        med = float(np.median(res))
        return med, float(np.median(np.abs(res - med)))
    sqm_rows = [o for o in out if o["kind"] == "sqm"]
    late = [o for o in sqm_rows if o["time"] and int(o["time"][:2]) < 5]
    med, mad = stats(out)
    med_sqm, mad_sqm = stats(sqm_rows)
    summary = {"n": len(out), "n_sqm": len(sqm_rows), "median_residual": med, "mad": mad,
               "median_residual_sqm": med_sqm, "mad_sqm": mad_sqm,
               "n_sqm_late": len(late), "median_residual_sqm_late": stats(late)[0]}
    return out, summary


def write_markdown(path, site_rows, anchor, gan_rows, gan_summary, gan_files):
    lines = [
        "# v2.0 sanity check",
        "",
        "*Generated by `python -m pipeline.build`. These comparisons check plausibility; they are not a calibration "
        "(PRD 0A.2). Every skyglow output stays labeled \"uncalibrated planning projection\".*",
        "",
        "## Corpus site values (Clear Dark Sky / IDA figures, PRD 6.5)",
        "",
        f"One global flux scale (alpha = {anchor['alpha']:.3f}) is fitted to these ten values; RMSE {anchor['rmse_mag']:.2f} mag.",
        "Coordinates are the approximate PRD 6.5 values (open item: verify).",
        "",
        "| Site | Corpus mag | Model mag | Residual |",
        "| --- | --- | --- | --- |",
    ]
    for s in site_rows:
        lines.append(f"| {s['name']} | {s['seed_mag']:.2f} | {s['model_mag']:.2f} | {s['residual']:+.2f} |")
    lines += ["", "## Globe at Night (not used in any fit)", ""]
    if not gan_summary["n"]:
        lines.append("No clear-sky Globe at Night observations fall inside the Module A grid.")
    else:
        lines += [
            f"{gan_summary['n']} clear-sky observations inside the Module A grid ({gan_summary['n_sqm']} with an SQM reading) from "
            f"{len(gan_files)} yearly files.",
            "",
            f"- **SQM readings** (instrumented, the meaningful comparison): median residual (model - observed) "
            f"{gan_summary['median_residual_sqm']:+.2f} mag, median absolute deviation {gan_summary['mad_sqm']:.2f} mag; "
            f"{gan_summary['n_sqm_late']} readings taken 00:00-05:00 have median residual {gan_summary['median_residual_sqm_late']:+.2f} mag.",
            f"- **All observations** including naked-eye limiting magnitudes: median residual {gan_summary['median_residual']:+.2f} mag, "
            f"median absolute deviation {gan_summary['mad']:.2f} mag.",
            "",
            "A positive residual means the model is darker than the observation. Evening naked-eye estimates are coarse "
            "(one-magnitude chart steps map to 0.5-1.5 mag/arcsec²) and taken before curfews, so a positive bias is expected.",
            "",
            "| Date | Lat | Lon | Type | Observed | Model | Residual |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for o in sorted(gan_rows, key=lambda x: x["date"] or ""):
            lines.append(f"| {o['date']} {o['time']} | {o['lat']:.3f} | {o['lon']:.3f} | {o['kind']} "
                         f"{'LM ' + str(int(o['limiting_mag'])) if o['kind'] == 'nelm' else ''} | {o['obs_mag']:.2f} | {o['model_mag']:.2f} | {o['residual']:+.2f} |")
    lines += ["", "Not yet compared: Clear Dark Sky chart pages and SQM figures inside IDA applications (research prompt S1 compiles them).", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
